### ISSUE TITLE
Change font

### ISSUE THREAD

**Issue by nickdnk** [T-Pham/Switch#3]
Hey

Really nice pod. However, I can't seem to easily change the font of the buttons. Could you perhaps create that feature? I'm a little busy so I don't have time to PR it at the moment.

Thanks

**Comment by T-Pham** [comment]
@nickdnk: The font of the "buttons" can be changed by changing the font of the `leftLabel` and `rightLabel`. Please refer to the documentation for more details: http://cocoadocs.org/docsets/RoundedSwitch/2.0.1/Classes/Switch.html#/s:vC13RoundedSwitch6Switch9leftLabelCSo7UILabel
Hope it helps.

**Comment by nickdnk** [comment]
Okay, cool. I was thinking of a general "change font" method to change both buttons at the same time, but I'll just do as you suggested :)
